### ISSUE TITLE
Giving multiple input examples

### ISSUE THREAD

**Issue by Globegitter** [node-machine/machine#4]
Is it somehow possible to give multiple examples for inputs?
E.g.
```js
    version: {
      friendlyName: 'Package version',
      description: 'The semantic version of the NPM package to install',
      example: ['~1.0.0', '>=0.0.1']
    }
```

Might just be a personal preference, but I often like seeing multiple examples, since it immediately can give a better idea for different usages.
So yeah if that feature does not exists, would love to see it.

**Comment by mikermcneil** [comment]
Definitely- perhaps the ability to specify `examples`?  That way there wouldn't be confusion with array types.

(BTW for authoritative type-checking/coercion reference, check out https://github.com/node-machine/machine/blob/master/test/input-validation.test.js and https://github.com/node-machine/machine/blob/master/test/output-coercion.test.js)

**Comment by mikermcneil** [comment]
@Globegitter moved to https://groups.google.com/forum/#!topic/node-machine/kXhcFfutMOM
