### ISSUE TITLE
Unexpected behaviour when inputting data via command line - Value of input changes

### ISSUE THREAD

**Issue by niekcandaele** [node-machine/machine#45]
Hello

As support for a sails app, I'm creating a machinepack to interface with the API of a 7 days to die server. However, during testing I noticed weird behaviour when inputting data via CLI. 

When I don't include a required input 'steamID', I get prompted for it and the machine works as expected
When I do include this input in the command, the value used in the machine is different than what I entered!

I've made a gist recreating the issue and code for the machine, hope it makes my problem clear enough.

https://gist.github.com/niekcandaele/f404745596f3561179c71f3ae8405321

**Comment by mikermcneil** [comment]
@niekcandaele hmm any chance this could be a string/number casting issue?

**Comment by mikermcneil** [comment]
(fwiw I didn't see anything suspicious in [this file when I looked](https://github.com/niekcandaele/machinepack-7Days-webapi/blob/e921f7f2ca761148d1cdaaf52db7e222bffd6763/machines/get-player-inventory.js))

**Comment by niekcandaele** [comment]
You are probably correct that it is a string/number issue.

I tested some more with this in mind, I defined the input once as string and once as number.
As a string, I have the same issue I had. As a number, it never worked.


I detailed these tests in a gist again
https://gist.github.com/niekcandaele/56ce72897d15e976f987e92fcf9069e1
