### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by berge616** [node-machine/machine#46]
Appears to be a memory leak in this module when called through  sails-mysql. Reproduced locally and took heap snapshots before any calls and then after running many calls through the api. Compared these heaps in chromes profiling and found an alarming number of debug closures being left in memory(both snapshots were taken immediately after forcing a garbage collection)

<img width="445" alt="screen shot 2017-12-15 at 11 03 00 am" src="https://user-images.githubusercontent.com/1350815/34050069-8a76195c-e187-11e7-8429-030274bcecbf.png">

Should be easily reproducible by installing sails v1 and connecting it to a mysql db with some basic routes to add a record to the db. 

Here is the code i used to get heap size and generate the snapshots:
 ```
npm install heapdump
const heapdump = require('heapdump');

  generateHeapDumpAndStats: function(req, res){
  //1. Force garbage collection every time this function is called
  try {
    global.gc();
  } catch (e) {
    console.log("You must run program with 'node --expose-gc index.js' or 'npm start'");
    process.exit();
  }

  //2. Output Heap stats
  var heapUsed = process.memoryUsage().heapUsed;
  console.log("Program is using " + heapUsed + " bytes of Heap.")
     res.status(200).json({heapUsed:heapUsed/1042/1024});

  //3. Get Heap dump
  //process.kill(process.pid, 'SIGUSR2');
     heapdump.writeSnapshot();
    }
```
These lines seem to be the culprit:

https://github.com/node-machine/machine/blob/13.0/lib/private/intercept-exit-callbacks.js#L260-L261
https://github.com/node-machine/machine/blob/13.0/lib/private/help-exec-machine-instance.js#L108-L110

I'm using the following versions:
```
    "sails": "^1.0.0-42",
    "sails-disk": "^1.0.0-12",
    "sails-hook-custom-blueprints": "^1.0.0",
    "sails-hook-grunt": "^3.0.0",
    "sails-hook-orm": "^2.0.0-22",
    "sails-mysql": "^1.0.0-15",
```

**Comment by mikermcneil** [comment]
Thanks @berge616!  The latest version of the machine runner doesn't use the `debug` dep, so we should be good in `machine` now.  That said, it's still an issue for older versions of the runner though, so I started on a solution here: https://github.com/balderdashy/sails/issues/4264#issuecomment-352611473

(For now, closing this issue to consolidate.  For the latest on how this affects Sails, see https://github.com/balderdashy/sails/issues/4264)
