### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by Zolmeister** [node-machine/machine#5]
Promise support via the popular [Bluebird](https://github.com/petkaantonov/bluebird) library would be great
[.catch([Function ErrorClass|Function predicate...], Function handler) -> Promise](https://github.com/petkaantonov/bluebird/blob/master/API.md#catchfunction-errorclassfunction-predicate-function-handler---promise)

(solves #3)

Example:

```js

module.exports = {
  inputs: {}
  exits: {
    success: {}
   aError: {}
   bError: {}
  }
  fn: (inputs, exits) {
    // normal stuff here
  }
}
```

Usage:

```js
var myMachine = require('mymachine')
myMachine.exec()
.then(function(success){})
.catch(myMachine.errors.aError, function(err){})
.catch(myMachine.errors.bError, function(err){})
.catch(function(uncaught){})
```

**Comment by particlebanana** [comment]
:dancers::notes::dancers::notes::dancers: 
https://www.youtube.com/watch?v=H8Q83DPZy6E

**Comment by robwormald** [comment]
i was thinking more along the lines of:
```js
//resolve on default, reject otherwise 
Github.getRepo(loginCred)
.exec()
.then((result) => console.log(result));

//register for exits in exec - they should return a value or promise.
Github.getRepos(repoDetails)
.exec({
  success(repos){ 
    //do more stuff
   return Promise.all(repos.map(Github.getCommitsForRepo))
  },
  token_expired(){
    //recover from failure
    return GitHub.login(newLoginCreds)
    .then(() => Github.getRepo(repoDetails).exec())
}})
.then((allRepos) => console.log(allRepos));
```

**Comment by sgress454** [comment]
@robwormald I think I get it now.  You're looking for a `finally` block, although in this case it makes sense to call it `then`.  There's something to this--we don't currently have a way of implementing "convergence" of two branches other than using a function to wrap the code they both want to call.  This solves that in a more elegant way.

**Comment by sgress454** [comment]
Here's a simple example of what I mean: an HTTP request machine that has exits for four responses, each of which does their own processing but then converges to one of two "do other stuff" machines.
![image](https://cloud.githubusercontent.com/assets/553428/6541082/d83cb74c-c473-11e4-95b8-be6fc590a8ec.png)
One way to write this is:
```
httpRequest({<inputs>}).exec({
   200: function(httpResponse) {
       doStuff({<inputs>}).exec({
         success: function(){doOtherStuff(httpResponse);}
       });
   },
   201: function(httpResponse) {
       doStuff({<inputs>}).exec({
         success: function(){doOtherStuff(httpResponse);}
       });
   },
   401: function(httpResponse) {
       doStuff({<inputs>}).exec({
         success: function(){doMoreStuff(httpResponse);}
       });
   },
   403: function(httpResponse) {
       doStuff({<inputs>}).exec({
         success: function(){doMoreStuff(httpResponse);}
       });
   },
});

function doOtherStuff(httpResponse) {
...codez...
}

function doMoreStuff(httpRequest) {
...codez...
}
```

Those two functions hanging out at the end do the trick, but it doesn't really capture the kind of flow we're going for.  If `doOtherStuff` and `doMoreStuff` where *chained* to the `httpRequest` call, that would be interesting.

**Comment by Zolmeister** [comment]
@sgress454 I would argue that any function which has more than one `success` exit is poorly constructed.

That being said, you could technically capture that idea using a 'success' error type like so:

```js
function doNotUse() {
  httpRequest({}).exec()
  // success branch
  .catch(httpRequest.successes.is200, function(){
    // do 200 specific stuff
  })
  .catch(httpRequest.successes.is201, function(){
    // do 201 specific stuff
   })
  .then(function() {
    // do merged 201 and 200 streams
    throw httpRequest.succcessWrapper({result})
  })
  // failure branch
  .catch(httpRequest.errors.is401, function() {
    // do stuff
  })
  .catch(httpRequest.errors.is403, function() {
    // do stuff
  })
  .then(function() {
    // do merged 401 and 403 streams
    throw httpRequest.succcessWrapper({result})
  })
}
```

But obviously if you're writing code like that you should consider using events and actual streams instead of promises. (see [Rx](https://github.com/Reactive-Extensions/RxJS))

**Comment by Zolmeister** [comment]
A more proper way to write your use case would be:

```js
function getResult() {
  httpRequest({}).exec()
  .then(function(req) {
    if (req.code === 201 || req.code === 200) {
      return (req.code === 200 ? 
         Promise.resolve(do200Stuff()) :
         Promise.resolve(do201Stuff())
      .then doMergedStuff
    } else {
     ...
    }
  })
}
```

**Comment by mikermcneil** [comment]
> I would argue that any function which has more than one success exit is poorly constructed.

I'd love to see this assertion backed up with some real world evidence.

**Comment by mikermcneil** [comment]
but seriously, consider `ifThen` and `findOne`.

```
if()
|_ then
|_ else
|_ error
```

```
findOne()
|_ success
|_ notFound
|_ error
```

**Comment by mikermcneil** [comment]
more here: http://youtu.be/72jI0dQx7pw?t=12m32s

**Comment by Zolmeister** [comment]
To be clear, multiple `exits` (error types) are perfectly valid (e.g. hardware can fail in unexpected ways, some of which are recoverable).

As for an example, @sgress454 provided a great one. 
httpRequest -> {200, 201, 401, 403}

**I'm not allowed to handle 200 and 201 the same way**
Because you took away my choice of using an `if` statement.

(I can handle 401 and 403 the same by only having an 'error()' handler)

In order to handle 200 and 201 the same way, I have to **duplicate code**
As he showed, `200 -> doOtherStuff(), 201 -> doOtherStuff()`

Now, if that doesn't seem so bad, let's consider the entire 2xx chain.
`200 -> doOtherStuff(), 201 -> doOtherStuff(), 202 -> doOtherStuff(), 203 -> doOtherStuff(), 204 -> doOtherStuff(), 205 -> doOtherStuff(), 206 -> doOtherStuff(), 207 -> doOtherStuff(), 208 -> doOtherStuff(), 209 -> doOtherStuff(), 210 -> doOtherStuff()`

The method of handling success is clearly broken.

**Comment by mikermcneil** [comment]
Guys, let's take this discussion to https://groups.google.com/forum/#!forum/node-machine

**Comment by mikermcneil** [comment]
@Zolmeister and PS. good point and funny timing- @sgress454 and I were just chatting about this earlier today.  Posted a proposed solution to the group

**Comment by mikermcneil** [comment]
@Zolmeister Support for promises is now implemented on the `lite` branch, with full support for async/await.
